name 'windows-security-policy'
maintainer 'Joe Gardiner'
maintainer_email 'joe@grdnr.io'
license 'Apache-2.0'
description 'Configures Windows security policy'
version '0.4.0'
supports 'windows'
issues_url 'https://github.com/grdnrio/windows-security-policy/issues'
source_url 'https://github.com/grdnrio/windows-security-policy'

chef_version '>= 17'
